server:
  port: ${PORT_GATEWAY}

spring:
  application:
    name: api-gateway
  http:
    codecs:
      max-in-memory-size: 10MB

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:${PORT_AUTH}
              predicates:
                - Path=/auth/**
            - id: board-service
              uri: http://board-service:${PORT_BOARD}
              predicates:
                - Path=/board/**
            - id: board-public-service
              uri: http://board-service:${PORT_BOARD}
              predicates:
                - Path=/board-public/**
              filters:
                - RewritePath=/board-public/(?<segment>.*), /board/board-public/${segment}
            - id: board-public-full-service
              uri: http://board-service:${PORT_BOARD}
              predicates:
                - Path=/board-public-full/**
              filters:
                - RewritePath=/board-public-full/(?<segment>.*), /board/board-public-full/${segment}
            - id: board-full-service
              uri: http://board-service:${PORT_BOARD}
              predicates:
                - Path=/board-full/**
              filters:
                - RewritePath=/board-full/(?<segment>.*), /board/board-full/${segment}
            - id: admin-service
              uri: http://admin-service:${PORT_ADMIN}
              predicates:
                - Path=/admin/**
app:
  fqdn: ${FQDN}
  play-fqdn: ${PLAY_FQDN:}
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /documentacion
    urls:
      - name: Auth Service
        url: auth/api-docs/auth
      - name: Board Service
        url: board/api-docs/board
      - name: Admin Service
        url: admin/api-docs/admin

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: INFO